### ISSUE TITLE
api call bug

### ISSUE THREAD

**Issue by ouyoung33** [jaredhendrickson13/pfsense-api#535] opened 2024-08-07 03:41 UTC
api call bug: When I manually create dnat,Nat will default "filter rule association" to "rule nat" to implement forwarding and connect to my internal machine; But when I create a dnat rule using the api, the "filter rule association" is "pass" but no forwarding is actually implemented, and I can't connect to my internal machine through dnat.
The scenario we are using now is as follows: using zerotrust to give the user portal access to the server, the api will be called before accessing the server to create a rule with a validity period; Our implementation is based on v1. At present, more users rely on this scheme. During operation and maintenance, there is no way to manually change the port-forward rule through the GUI
Therefore, I would like to ask if this requirement /Bug can be modified in v1, and when will the version be released? Or whether other command lines can be used to change the port forward

**Comment by jaredhendrickson13** [comment] 2024-08-08 16:43
Duplicate of #533

**Closed by jaredhendrickson13** 2024-08-08 16:43 UTC
