### ISSUE TITLE
How should I know what the client-token is if it is cut-off when longer than 20 characters?

### ISSUE THREAD

**Issue by Tristanhx** [jaredhendrickson13/pfsense-api#152] opened 2021-08-13 10:03 UTC
https://github.com/jaredhendrickson13/pfsense-api/blob/ad249d8c5324c8e2c4a78939e00e426708412c31/pfSense-pkg-API/files/usr/local/www/api/index.php#L292

**Comment by jaredhendrickson13** [comment] 2021-08-14 05:10
Hey!

This appears to be a duplicate of #103. That is a hash of the client token, not the token itself. The token only appears once after generating in the confirmation banner towards the top. Refer to #103 for more info. 

Thanks!

**Closed** 2021-08-14 05:10 UTC
Labels: duplicate
