### ISSUE TITLE
Add support for created Filter rule association when creating port forward

### ISSUE THREAD

**Issue by lechuhuuha** [jaredhendrickson13/pfsense-api#516] opened 2024-07-19 01:34 UTC
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**

https://docs.netgate.com/pfsense/en/latest/nat/port-forwards.html

![image](https://github.com/user-attachments/assets/40af9be3-421c-4546-ad9a-965fc3487532)

**Is your feature request related to a problem? Please describe.**

When i created port forward there is a option in the web ui that allow created rule association  with the port forward.
In the api there is also a field (associated_rule_id) like in web ui  but its only have 2 option is [empty, pass]

**Describe the solution you'd like**
The field associated_rule_id should also support options [add-associated] 

Example image: 
![image](https://github.com/user-attachments/assets/1849fc8c-d0d4-489f-b97f-1528129108a7)

**Describe alternatives you've considered**
 I tried to add to fork the repo and add the field myself then run github action to build the pkg. But can not setup runner in FreeBSD

FreeBSD pfSense.home.arpa 14.0-CURRENT FreeBSD 14.0-CURRENT amd64 1400094

**Additional context**
None

**Comment by jaredhendrickson13** [comment] 2024-07-22 17:48
Duplicate of #275. You can refer to the [contributors guide](https://pfrest.org/CONTRIBUTING/#building-the-package-from-source) for instructions on building the package from your fork if needed.

**Closed by jaredhendrickson13** 2024-07-22 17:48 UTC
Labels: feature request, backlog
