### ISSUE TITLE
Not Basic and Api key standard authentication 

### ISSUE THREAD

**Issue by tbaror** [jaredhendrickson13/pfsense-api#187] opened 2022-01-07 13:37 UTC
**Expected behavior**
Able to authenticate Basic or api key
**Screenshots or Response**
![Screenshot 2022-01-07 153331](https://user-images.githubusercontent.com/217691/148551498-19fce48b-2346-4580-968f-8fd390f12852.png)

**pfSense Version & Package Version:**
 - pfSense Version: 2.5.2
 - Package Version  v1.3.3
Hello 
I am trying use this great api package with our [SOAR](https://shuffler.io/) system ,which let me automate security workflows
The issue is that is the authentication is seems not be standard regarding Basic auth or api key as i have  with those tools option to build the integration or even when i test with tool like Postman , i must enter the auth part as the parameters or i am doing something wrong
Please advise
Thanks

**Comment by pincher95** [comment] 2022-01-09 09:46
Hi Tal,
There is no basic authentication, this one in my personal wish list, authenticating via Local DB is part of payload as mentioned in documentation {"client-id": "admin", "client-token": "pfsense"}.
To make Local DB authentication act as basic authentication the change is fairly simple, the function located at:

/etc/inc/api/framework/APIAuth.inc

    private function authenticate_local_database() {
        $this->username = $_SERVER['PHP_AUTH_USER'];
        // Authenticate against local database
        if (authenticate_user($this->username, $_SERVER['PHP_AUTH_PW'])) {
            // Ensure user is not disabled
            if (APITools\is_user_disabled($this->username) === false) {
                unset($_SESSION["Username"]);
                $_SESSION["Username"] = $this->username;
                return true;
            }
        }
        return false;
    }

rebuild API end points:
/usr/local/share/pfSense-pkg-API/manage.php buildendpoints

**Comment by tbaror** [comment] 2022-01-09 20:27
> 

Thanks works like charm , hope to see it implemented in the upstream code
Thank you

**Comment by jaredhendrickson13** [comment] 2022-01-12 04:42
Thanks @pincher95 for the great insight. 

Since this appears to be a duplicate of #174 I will close out this issue. I will provide an update on #174 once this has been implemented on the next release's branch. 

Thanks!

**Closed by jaredhendrickson13** 2022-01-12 04:42 UTC
