### ISSUE TITLE
Cannot get IDs of "Read Routing Gateway"

### ISSUE THREAD

**Issue by edenzv** [jaredhendrickson13/pfsense-api#110] opened 2021-03-21 15:45 UTC
Hi,

I want to delete routing gateway but I cannot find the ID in the request of "Read Routing Gateway".

Thanks Eden

**Comment by jaredhendrickson13** [comment] 2021-03-21 16:36
Hey!

This is because pfSense doesn't store object IDs, rather they use the configuration array index value of the object. This is outlined in the documentation [here](https://github.com/jaredhendrickson13/pfsense-api/tree/v120#obtaining-object-ids). Or you can refer to #90 for some examples and info on future plans for obtaining object IDs.

Let me know if you have any troubles. 

Thanks!

**Comment by edenzv** [comment] 2021-03-22 16:23
Hey, 

Thanks o the quick response, I also did your recommend before and tried it again, but I tried to remove by the ID and it remove other that I didn't meant to remove:

This is the gateways list in pfSense webgui:
![image](https://user-images.githubusercontent.com/10780609/112021784-50821b00-8b3a-11eb-8b7e-9e8e9512f1cb.png)

This is the output of GET https://pfSense/api/v1/routing/gateway in postman:
![image](https://user-images.githubusercontent.com/10780609/112022069-9808a700-8b3a-11eb-8670-b39d832a093a.png)

I need to removed "WANCP1" and from the documentation this ID is 1 but it removed a different gateway (LANGW):
![image](https://user-images.githubusercontent.com/10780609/112022572-19f8d000-8b3b-11eb-8818-8ee13dc9bb17.png)

And after check the gateway list I found that it removed different gateway (WAN11):
![image](https://user-images.githubusercontent.com/10780609/112022777-47457e00-8b3b-11eb-9872-88be060718ce.png)

I hope that you  understood this use case.

Thanks Eden

**Comment by jaredhendrickson13** [comment] 2021-03-22 17:23
Thanks for these details. Looking further into the code, I do see there is a discrepancy on this endpoint between the GET and DELETE requests. Typically, GET requests read the pfSense configuration directly but in this case the function it calls seems to return some detailed backend values for gateways that are not expected.

In the short term, I do see a workaround you can use today. Making a GET request to /api/v1/routing/gateway does seem to return the ID within the response data itself, more specifically the `attribute` field of the object is the ID. If the object does not contain a numeric value in the `attribute` field, it cannot be deleted as it's a system-defined gateway. 

For example, GET requests to /api/v1/routing/gateway currently return this:
```json
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "EXAMPLE_GW_1": {
      "interface": "em0",
      "gateway": "172.16.209.2",
      "name": "EXAMPLE_GW_1",
      "weight": "1",
      "ipprotocol": "inet",
      "descr": "",
      "monitor": "172.16.209.2",
      "friendlyiface": "wan",
      "friendlyifdescr": "WAN",
      "attribute": 0,    # <----- This object uses ID 0
      "tiername": ""
    },
    "EXAMPLE_GW_2": {
      "interface": "em0",
      "gateway": "172.16.209.12",
      "name": "EXAMPLE_GW_2",
      "weight": "1",
      "ipprotocol": "inet",
      "descr": "",
      "monitor": "172.16.209.12",
      "friendlyiface": "wan",
      "friendlyifdescr": "WAN",
      "attribute": 1,    # <----- This object uses ID 1
      "tiername": ""
    },
    "Null4": {
      "name": "Null4",
      "interface": "lo0",
      "ipprotocol": "inet",
      "gateway": "127.0.0.1",
      "attribute": "system",    # <----- This object cannot be deleted as it is a system gateway
      "tiername": ""
    }
  }
}
```

In the long term, this does express the need to move the current GET response to a different endpoint that can be used to retrieve these more detailed/non-configuration gateway values. Then in it's place, the GET response for this endpoint should be refactored to only return gateways as they appear in the configuration. Since this requires a breaking change, I will include the code change in the v1.3.0 workflow. For now, I will add a snippet to the documentation that details this discrepancy in the next release (v1.2.0). I'll keep this issue updated as these changes are implemented.

Thanks again for pointing this out. I appreciate it.

**Comment by edenzv** [comment] 2021-03-24 13:17
Hey,

I'm very appreciate your advices.
I tried the workaround of remove the attribute, and I got response that it removed the right gateway but it removed a different gateway:

Need to removed "WANCP_Internet", and the attribute is 5:
![image](https://user-images.githubusercontent.com/10780609/112315422-cdd09b80-8cb2-11eb-9ec8-830dfa5d8e36.png)

Send delete request and got response that it removed:
![image](https://user-images.githubusercontent.com/10780609/112315561-ee005a80-8cb2-11eb-9295-b03855cd5a20.png)

I see the list of the existing gateways and see that "WANCP_Internet" is existing and "WANGW_2" has been removed:
![image](https://user-images.githubusercontent.com/10780609/112316491-d37ab100-8cb3-11eb-9353-fb1fa4abbf02.png)


I hope that you understood this use case.

Thanks Eden

**Comment by jaredhendrickson13** [comment] 2021-03-25 18:27
Thanks for your patience.I spent some time yesterday looking deeper into this and I did find that in some scenarios the IDs become misaligned from the configuration, which seems to be what is causing this. I found I was able to reproduce this when either:
1) the gateway order has been re-arranged within the UI
2) gateways exist for multiple interfaces and were added out of order, or a gateway was deleted

I can actually reproduce the mismatched ID in the pfSense UI as well, however, it seems to work some magic to somehow map this magic ID back to it's actual ID which is something the API endpoint is missing. I'll work on a fix for this and have it included in the next patch. I'll update this issue when I have a pull request for the patch, which will include a test build so you can verify it fixes this issue for you.

Thanks again!

**Closed** 2021-03-31 21:40 UTC
Labels: breaking change, bug, documentation
