### ISSUE TITLE
Wish: Consistent types/schema on fields

### ISSUE THREAD

**Issue by jared-gs** [jaredhendrickson13/pfsense-api#134] opened 2021-05-08 13:19 UTC
The API currently accepts and produces fields that can sometimes be different types. For example, the "tracker' can sometimes be a string or an integer depending on the operation, [FIREWALL/RULE](https://github.com/jaredhendrickson13/pfsense-api#firewallrule).

```
POST api/v1/firewall/rule
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
...
    "descr": "This is a test rule added via API",
    "tracker": 1620096674,
...
  }
}
```

```
GET api/v1/firewall/rule
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
...
    "descr": "This is a test rule added via API",
    "tracker": "1620096674",
...
  }
}
```

This is problematic for statically typed languages such as Go. Unmarshalling JSON into an object field, which is of a single type, requires custom unmarshalling logic if there are varying types. Other fields such as `icmptype` can be strings or arrays of strings and is also difficult to navigate. 

My feature request is these response fields should be consistent schema across all categories and operations, which enables better support for maintaining client libraries.

**Comment by jaredhendrickson13** [comment] 2021-05-11 21:22
Hey!

This is likely a duplicate of #24 and/or #41 which will be addressed in v2.0.0. This happens because pfSense uses an XML based configuration that is only parsed into strings and/or arrays (if more than 1 string is nested) whenever data is read from the configuration file. In comparison, when data is created or updated in PHP at runtime additional data types such as booleans and integers are allowed. A representation layer is required to translate the data from the XML file to their appropriate RESTful data type. Doing so will take quite a bit of work and will fundamentally change the way the API processes requests and formats responses which is why it is a v2.0.0 item. There is a v2.0.0 project board on the repo that will track the progress. 

Thanks!

**Closed by jaredhendrickson13** 2021-05-11 21:22 UTC
