### ISSUE TITLE
WireGuard API Rest

### ISSUE THREAD

**Issue by lostitguy** [jaredhendrickson13/pfsense-api#328] opened 2023-03-06 17:10 UTC
Good Afternoon,

I have installed the Wireguard package into PFSense.  I was wondering of PFSense-API will work with Wireguard.  Primarily the create user function and output that info to a txt file on local machine.  My main issue is just trying to find the Wireguard API url's.  Thank you and have a great day.

**Comment by jaredhendrickson13** [comment] 2023-03-07 16:53
Hey!

Thanks for reaching out. This looks to be a duplicate of #158. There are no endpoints for managing WireGuard yet. This is a request I get quite often though so it will likely be included in the somewhat near future. There is a larger refactor coming soon in order to support pfSense 2.7.0 and pfSense Plus 23.01, so new features are on hold until that is done. In the meantime, follow the original feature request (#158) for updates on this feature going forward.

Thanks again!

**Closed by jaredhendrickson13** 2023-03-07 16:53 UTC
Labels: feature request, backlog
