### ISSUE TITLE
nat port_forward associated-rule (associated-rule-id)

### ISSUE THREAD

**Issue by Harryols** [jaredhendrickson13/pfsense-api#318] opened 2023-02-15 20:18 UTC
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
When you update something via the pfSense ui, it will not reset the associated-rule to "pass"
In pfSense ui you can select generate new associated-rule based on the port_forward

**Is your feature request related to a problem? Please describe.**
The associated-rule-id will reset to "pass" every time i put anything on port_forward

**Describe the solution you'd like**
The Ability to preserve current associated-rule-id
The Ability to put another existing associated-rule-id on port_forward
The Ability to generate a new associated-rule based on port_forward via the "new" value in ui

**Describe alternatives you've considered**
Delete and create the port_forward, but that has the same problem - a new associated-rule can't be generated.

**Comment by jaredhendrickson13** [comment] 2023-02-16 01:00
Duplicate of #148, feel free to follow and upvote that issue. Feature requests are on a freeze until pfSense 2.7.0 releases due to the large refactor associated.

**Closed by jaredhendrickson13** 2023-02-16 01:00 UTC
Labels: feature request, backlog
