### ISSUE TITLE
Inconsistent types in http response

### ISSUE THREAD

**Issue by pincher95** [jaredhendrickson13/pfsense-api#175] opened 2021-11-03 08:51 UTC
**Is your feature request related to existing pfSense functionality that is missing from the API? Please describe.**
https://127.0.0.1/api/documentation/#FIREWALL_2FRULE

**Is your feature request related to a problem? Please describe.**

Different response type in some fields, for example for

curl  -XDELETE 'https://127.0.0.1/api/v1/firewall/rule and curl  -XGET 'https://127.0.0.1/api/v1/firewall/rule
.data.created.time, .data.updated.time and .data.tracker is of type string

curl  -XPOST 'https://127.0.0.1/api/v1/firewall/rule 
.data.created.time, .data.updated.time and .data.tracker is of type int

curl  -XPUT 'https://127.0.0.1/api/v1/firewall/rule 
.data.created.time,  .data.tracker is of type string
.data.updated.time is of type int

This is just an example I am sure it's across the board 

**Describe the solution you'd like**

Standardize http response to any request in

 same field to string or int for example

.data.created.time, .data.updated.time and .data.tracker is of type string

OR

.data.created.time, .data.updated.time and .data.tracker is of type int   

**Additional context**

![delete_response](https://user-images.githubusercontent.com/51751791/140031629-60b392ce-fe38-4db9-90e7-0e32f1a2e36f.PNG)
![get_response](https://user-images.githubusercontent.com/51751791/140031633-e3f1c142-3dcb-4995-80ec-afb927822637.PNG)
![post_response](https://user-images.githubusercontent.com/51751791/140031634-b0a3a345-7d66-473f-ad59-cb4286453a30.PNG)
![put_response](https://user-images.githubusercontent.com/51751791/140031635-f672e166-dd62-4443-9be4-1185f9fe1fde.PNG)

**Comment by jaredhendrickson13** [comment] 2021-11-04 22:52
Hey!

This looks to be a duplicate of #41 and #173. In summary, most if not all data typing is lost when data is written to the XML configuration. This is because pfSense only parses it's XML configuration as strings and arrays of strings. A translation piece would need to written for each endpoint that converts the response back to the accepted input format. That is an item that's planned for v2.0.0 but given the complexity this adds it will be some time before such a thing will be integrated. Keep an eye on #41 for any progress being made in the meantime.

Thanks!

**Closed by jaredhendrickson13** 2021-11-04 22:52 UTC
Labels: duplicate
